language: java

jdk:
 - openjdk6
 - openjdk7

before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -y ant
 - sudo apt-get install -y ecj

 - export PORTLET=${PWD}
 - export INSTALL_ROOT=${HOME}/liferay-portal-6.1.1-ce-ga2
 - env
 - mkdir -p ${INSTALL_ROOT}/deploy
 - mkdir -p ${INSTALL_ROOT}/glassfish-3.1.2/autodeploy
 - mkdir -p ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/applications/liferay-portal/WEB-INF/lib
 - mkdir -p ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/applications/liferay-portal/WEB-INF/tld
 - cd ${HOME}

# Get the Liferay portal with the GlassFish application server (v3.1.2)
 - wget http://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.1.1%20GA2/liferay-portal-glassfish-6.1.1-ce-ga2-20120731132656558.zip/download -O liferay-portal-glassfish-6.1.1-ce-ga2-20120731132656558.zip
 - unzip liferay-portal-glassfish-6.1.1-ce-ga2-20120731132656558.zip

# Install additional dependencies
 - wget http://grid.ct.infn.it/statistics/plugins/lib.tar.gz
 - tar zxvf lib.tar.gz -C ${INSTALL_ROOT}/glassfish-3.1.2/domains/domain1/

# Get the SDK and unpack it
 - wget http://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.1.1%20GA2/liferay-plugins-sdk-6.1.1-ce-ga2-20121004092655026.zip/download -O liferay-plugins-sdk-6.1.1-ce-ga2-20120731132656558.zip
 - unzip liferay-plugins-sdk-6.1.1-ce-ga2-20120731132656558.zip
 - ls -lht ${INSTALL_ROOT}/*

# Get the build.properties
 - wget http://grid.ct.infn.it/statistics/plugins/build.properties
 - cp build.properties liferay-plugins-sdk-6.1.1
 - cp -r ${PORTLET} liferay-plugins-sdk-6.1.1/portlets

# Get the ecj.jar
 - wget http://grid.ct.infn.it/statistics/ecj.jar
 - sudo cp ecj.jar /usr/share/ant/lib/

# Building the semantic-search-portlet
install:
 - cd liferay-plugins-sdk-6.1.1/portlets/test_semantic
 #- sudo ant all

notifications:
  email:
    recipients:
        - giuseppina.inserra@ct.infn.it
        - carla.carrubba@ct.infn.it
